[package]
name = "example_async_channel"
version = "0.0.0-local"
authors = ["alshdavid"]
edition = "2021"
license = "MIT"

[dependencies]
edon = { path = "../../packages/edon" }
anyhow = "*"
async-channel = "2.3.1"