[package]
name = "edon"
version = "0.0.11"
authors = ["David Alsh"]
repository = "https://github.com/alshdavid/edon"
description = "Library embedding Nodejs (libnode) within Rust"
edition = "2021"
license = "MIT"

[lib]

[dependencies]
libffi = "^4.0.0"
libnode_sys = "^0.0.2"
